# Generated by Django 2.2.6 on 2019-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanuman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='profession',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='programmer',
            name='skills',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
